### PR TITLE
Repos + Fixes + Other

### PR DESCRIPTION
**Pull request by Ryan-Carstens**

### CODE REVIEW

**Comment by boniface** [comment]
Please fix Conflicting files

**Comment by Ryan-Carstens** [comment]
please advise

**Comment by boniface** [comment]
not working

**Comment by Ryan-Carstens** [comment]
How do I see where the conflicts are? All I did was add packages of each domain and other respective derivative objects. 

Complaint.scala and Contract.scala are not much different and seem perfectly fine to me, 

Please help me

**Comment by Ryan-Carstens** [comment]
please see that I changed the classes back to their old code

**Comment by Ryan-Carstens** [comment]
I have tried fixing manually but this is just a mess.

I had changed both Complaint.scala and Contract.scala back to their original code, 

Only adding them each into their own package - only change

pulled the code to get HEAD additions into my own repo, and I dont see any conflicts there?

Im really confused and now all my other code cannot be pushed just because of these two classes?

**Comment by boniface** [comment]
everybody has been  fixing their own conflicts ..I don't fix people's conflicts, but just reject PR with conflicts. That is my job

**Comment by Ryan-Carstens** [comment]
I will attend then to fixing my code, and try my best to resolve these
conflicts as instructed.
Dr Kabaso, please understand I may only try and fix the merge this
afternoon/evening when I am home, as I work full day.

Thank you for your patience

Kind Regards

**Comment by Ryan-Carstens** [comment]
Good Morning,

Please will you see my pull request from yesterday on opsapi.

thank you kindly Dr Kabaso.

Regards

**Pull request closed without merging**
